export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FAILED_FETCH_MOVIES = 'FAILED_FETCH_MOVIES';
export const SUCCESS_FETCH_MOVIES = "SUCCESS_FETCH_MOVIES";

export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FAILED_SEARCH_MOVIE = 'FAILED_SEARCH_MOVIE';
export const SUCCESS_SEARCH_MOVIE = 'SUCCESS_SEARCH_MOVIE';
